# Site
name: 'Tony Ko'
description: 'My blog of Learning Journey.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'http://tainenko.github.io/'
disqus: 'tonys-blog-on-github'
email: 'tainenko@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-crosspost-to-medium

authors:
  tony:
    name:           Tony
    site:           https://tainenko.github.io
    avatar:         assets/images/avatar3.png
    bio:            "Hi, I am Tony, the author of Learning Journey blog. I hope you like what I sharing!"
    email:          tainenko@gmail.com
    twitter:        https://twitter.com/tainenko

  sal:
    name:           Sal
    site:           https://www.wowthemes.net
    avatar:         assets/images/avatar1.jpg
    bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    email:          wowthemesnet@gmail.com
    twitter:        https://twitter.com/wowthemesnet

  jane:
    name:           Jane
    site:           https://www.wowthemes.net
    avatar:         assets/images/avatar2.jpg
    bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email:          fakemail@gmail.com
    twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: tony
      avatar: /assets/images/avatar3.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Google Analytics
google_analytics: UA-139590916-1

# jekyll crosspost to medium
jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: public
  license: all-rights-reserved
  text: '<p>Give me 50 claps if you liked this article and subscribe</p><p>This was originally posted <a href="https://tainenko.github.io/"><em> on my own site</em></a>.</p>'
  backdate: true


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
