name: Jekyll Deploy
on: [push]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Run Jekyll
      uses: docker://faph/action-jekyll:1.5
      env:
        MEDIUM_INTEGRATION_TOKEN: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}
        MEDIUM_USER_ID: ${{ secrets.MEDIUM_USER_ID }}
